# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brian Perry
tagline:          'Web Developer'
description:      'Web Developer'
url:              https://backlineint.github.io
baseurl:          /bp_interactive/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate, jekyll-gist]
