# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Brian Perry
tagline:          'Web Developer'
description:      'Web Developer'
url:              https://backlineint.github.io
baseurl:          /

author:
  name:           'Brian Perry'
  url:            https://twitter.com/bricomedy

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/backlineint/backlineint.github.io

gems: [jekyll-paginate, jekyll-gist]
